ffmpeg (7:4.2.2-1ultinous1) bionic

diff --git a/ffmpeg/debian/rules b/ffmpeg/debian/rules
--- a/ffmpeg/debian/rules
+++ b/ffmpeg/debian/rules
@@ -15,6 +15,7 @@ include /usr/share/dpkg/architecture.mk
 export DEB_LDFLAGS_MAINT_STRIP=-Wl,-Bsymbolic-functions
 
 # Package name for the extra flavor.
+SHLIB_PKGS := $(shell sed -nr '/extra/! s/^Package:[[:space:]]*(lib.*[0-9]+)[[:space:]]*$$/\1/p' debian/control)
 EXTRA_PKGS := $(shell sed -nr 's/^Package:[[:space:]]*(.*extra[0-9]+)[[:space:]]*$$/\1/p' debian/control)
 FLAVORS = standard extra static
 
@@ -24,48 +25,89 @@ FLAVORS = standard extra static
 # The following flags are not added, because the necessary libraries are not in Debian:
 #   --enable-decklink
 #   --enable-libcelt                (see #676592: removed from Debian as abandoned upstream, replaced by opus)
+#   --enable-libdav1d
+#   --enable-libdavs2               (only in experimental)
 #   --enable-libilbc                (see #675959 for the RFP bug)
+#   --enable-libklvanc
 #   --enable-libkvazaar
 #   --enable-libmfx
 #   --enable-libopenh264
-#   --enable-libvidstab             (see #709193 for the RFP bug)
+#   --enable-libtensorflow
 #   --enable-libvmaf
-#   --enable-libxavs
-#   --enable-libzimg
+#   --enable-libxavs2
+#   --enable-libxavs                (only in experimental)
+#   --enable-libzimg                (see #864888 for the RFP bug)
+#   --enable-vapoursynth            (see #833942 for the RFP bug)
 # The following flags are not added for various reasons:
+#   --enable-crystalhd              Not usable in Debian (firmware missing from the archive - see #917292)
 #   --enable-librtmp                ffmpeg has better built-in RTMP support with listen mode.
+#   --enable-mbedtls                Already using gnutls as TLS implementation
 #   --enable-libmodplug             see #849840: replaced with libopenmpt
+#   --enable-libsrt                 see #933180: links against OpenSSL (license incompatibility)
 #   --enable-libv4l2                This is only needed for very old devices and may cause problems for others.
 #                                   Should anyone need it, using LD_PRELOAD pointing on libv4l2 has the same effect.
-#   --enable-opencl                 This is considered an experimental API.
+#   --enable-opencv                 Does not build with OpenCV >= 3.4
+#   --enable-pocketsphinx           see #941377: package dependencies are slightly broken
+# The following flags are not added by Ultinous, because necessary libraries are not in Ubuntu Bionic:
+#   --enable-libaom \
+#   --enable-libvidstab \
+# Ultinous does not need the following flags:
+#   --enable-libmysofa \
+
 CONFIG := --prefix=/usr \
 	--extra-version="$(DEB_REVISION)" \
 	--toolchain=hardened \
 	--libdir=/usr/lib/$(DEB_HOST_MULTIARCH) \
 	--incdir=/usr/include/$(DEB_HOST_MULTIARCH) \
+	--arch=$(DEB_HOST_ARCH_CPU) \
 	--enable-gpl \
 	--disable-stripping \
-	--enable-avfilter \
-	--enable-avresample \
-	--enable-version3 \
-	--enable-bzlib \
-	--enable-gpl \
-	--enable-iconv \
-	--enable-network \
-	--enable-postproc \
-	--enable-ffplay \
+	--enable-avresample --disable-filter=resample \
+	--enable-avisynth \
+	--enable-gnutls \
+	--enable-ladspa \
+	--enable-libass \
+	--enable-libbluray \
+	--enable-libbs2b \
+	--enable-libcaca \
+	--enable-libcdio \
+	--enable-libcodec2 \
+	--enable-libflite \
+	--enable-libfontconfig \
 	--enable-libfreetype \
+	--enable-libfribidi \
+	--enable-libgme \
+	--enable-libgsm \
+	--enable-libjack \
+	--enable-libmp3lame \
+	--enable-libopenjpeg \
+	--enable-libopenmpt \
+	--enable-libopus \
 	--enable-libpulse \
+	--enable-librsvg \
+	--enable-librubberband \
+	--enable-libshine \
+	--enable-libsnappy \
+	--enable-libsoxr \
+	--enable-libspeex \
+	--enable-libssh \
+	--enable-libtheora \
+	--enable-libtwolame \
 	--enable-libvorbis \
-	--enable-libx264 \
+	--enable-libvpx \
+	--enable-libwavpack \
+	--enable-libwebp \
 	--enable-libx265 \
-	--enable-libxcb \
-	--enable-libxcb-shm \
-	--enable-libxcb-xfixes \
+	--enable-libxml2 \
 	--enable-libxvid \
-	--enable-nvenc \
+	--enable-libzmq \
+	--enable-libzvbi \
+	--enable-lv2 \
+	--enable-omx \
+	--enable-openal \
+	--enable-opencl \
 	--enable-opengl \
-	--enable-xlib
+	--enable-sdl2
 
 # The standard configuration only uses the shared CONFIG.
 CONFIG_standard = --enable-shared
@@ -74,7 +116,13 @@ CONFIG_standard = --enable-shared
 CONFIG_extra = --enable-shared \
 	--enable-version3 \
 	--disable-doc \
-	--disable-programs
+	--disable-programs \
+	--enable-libaribb24 \
+	--enable-liblensfun \
+	--enable-libopencore_amrnb \
+	--enable-libopencore_amrwb \
+	--enable-libtesseract \
+	--enable-libvo_amrwbenc
 
 # The static libraries should not be built with PIC.
 CONFIG_static = --disable-pic \
@@ -95,15 +143,29 @@ ifneq ($(CXX),g++)
 	CONFIG += --cxx=$(CXX)
 endif
 
-# ffmpeg is involed in build-dependency cycles with opencv, x264 and chromaprint, so disable them in stage one.
+# Some libraries are built only on linux.
+ifeq ($(DEB_HOST_ARCH_OS),linux)
+	CONFIG += --enable-libdc1394 \
+		--enable-libdrm \
+		--enable-libiec61883
+endif
+
+# Ultinous does not need it
+## Enable nvenc on amd64 only; not supported on other architectures.
+#ifeq ($(DEB_HOST_ARCH),amd64)
+#	CONFIG += --enable-nvenc
+#endif
+
+# ffmpeg is involved in build-dependency cycles with x264 and chromaprint, so disable them in stage one.
 # Also disable frei0r, which build-depends on opencv.
-ifneq ($(filter stage1,$(DEB_BUILD_PROFILES)),)
+ifneq ($(filter pkg.ffmpeg.stage1,$(DEB_BUILD_PROFILES)),)
 	CONFIG += --disable-frei0r \
 		--disable-chromaprint \
-		--disable-libopencv \
 		--disable-libx264
 else
-	CONFIG += --enable-libx264
+	CONFIG += --enable-chromaprint \
+		--enable-frei0r \
+		--enable-libx264
 endif
 
 # Disable altivec optimizations on powerpc, because they are not always available on this architecture.
@@ -125,17 +187,27 @@ ifneq (,$(filter $(DEB_HOST_ARCH),x32))
 	CONFIG += --disable-asm
 endif
 
+
+
 # Disable some optimizations on mips*, because they are not always available on these architectures
-ifneq (,$(filter $(DEB_HOST_ARCH),mips mipsel mips64 mips64el))
+ifneq (,$(filter mips%r6 mips%r6el, $(DEB_HOST_ARCH)))
+	MIPS_R2_R6_CONFIG = --disable-mips32r2 \
+		--disable-mips64r2
+else
+	MIPS_R2_R6_CONFIG = --disable-mips32r6 \
+		--disable-mips64r6
+endif
+
+ifneq (,$(filter mips%, $(DEB_HOST_ARCH)))
 	CONFIG += --disable-mipsdsp \
 		--disable-mipsdspr2 \
 		--disable-loongson2 \
 		--disable-loongson3 \
 		--disable-mmi \
 		--disable-mips32r5 \
-		--disable-mips32r6 \
-		--disable-mips64r6 \
-		--disable-msa
+		$(MIPS_R2_R6_CONFIG) \
+		--disable-msa \
+		--disable-msa2
 endif
 
 # Disable mipsfpu on mips and mipsel, because it is not compatible with the FPXX ABI
@@ -143,11 +215,14 @@ ifneq (,$(filter $(DEB_HOST_ARCH),mips mipsel))
 	CONFIG += --disable-mipsfpu
 endif
 
+# Disable some tests which fail when FLT_EVAL_METHOD != 0 (found on i386, m68k and s390x)
+ifneq (,$(filter $(DEB_HOST_ARCH_CPU),i386 m68k s390x))
+	CONFIG += --ignore-tests=hapenc-hap-none,hapenc-hapa-none,hapenc-hapq-none
+endif
+
 # Set cross-build prefix for compiler, pkg-config...
-# Cross-building also requires to manually set architecture/OS.
 ifneq ($(DEB_BUILD_GNU_TYPE),$(DEB_HOST_GNU_TYPE))
 	CONFIG += --cross-prefix=$(DEB_HOST_GNU_TYPE)- \
-		--arch=$(DEB_HOST_ARCH) \
 		--target-os=$(DEB_HOST_ARCH_OS)
 endif
 
@@ -158,7 +233,7 @@ endif
 # Add configuration options:
 override_dh_auto_configure:
 	$(foreach flavor,$(FLAVORS),mkdir -p debian/$(flavor);)
-	$(foreach flavor,$(FLAVORS),set -e; echo " *** $(flavor) ***"; cd debian/$(flavor); ../../configure $(CONFIG) $(CONFIG_$(flavor)) || (cat config.log && exit 1); cd ../.. ;)
+	$(foreach flavor,$(FLAVORS),set -e; echo " *** $(flavor) ***"; cd debian/$(flavor); ../../configure $(CONFIG) $(CONFIG_$(flavor)) || (cat ffbuild/config.log && exit 1); cd ../.. ;)
 
 # Remove the subdirectories generated for the flavors.
 override_dh_auto_clean:
@@ -166,7 +241,7 @@ override_dh_auto_clean:
 
 # Create doxygen documentation:
 override_dh_auto_build-indep:
-	dh_auto_build -i --sourcedirectory=debian/standard -- apidoc
+	dh_auto_build -i --sourcedirectory=debian/standard -- apidoc documentation
 	# Create the minified CSS files.
 	#  Due to https://github.com/nodejs/node/issues/14752 where nodejs will
 	#  leave set O_NONBLOCK on stderr, we pipe stderr through cat which will
@@ -217,31 +292,26 @@ endif
 	install -m 644 debian/static/*/lib*.a debian/tmp/usr/lib/$(DEB_HOST_MULTIARCH)
 
 override_dh_auto_install-indep:
-	dh_auto_install -i --sourcedirectory=debian/standard
+	$(MAKE) -C debian/standard DESTDIR=$(CURDIR)/debian/tmp install-doc install-examples
+	# Create index.html page for the FFmpeg manual
+	cd debian/tmp/usr/share/doc/ffmpeg && tree -H '.' -L 1 -P '*.html' --noreport --charset utf-8 -T 'FFmpeg Manual Index' -o index.html
 
 override_dh_install:
 	dh_install $(addprefix -p,$(EXTRA_PKGS)) --sourcedir=debian/tmp/extra
 	dh_install --remaining-packages
 
-override_dh_makeshlibs:
-	set -e && for pkg in $(shell dh_listpackages -a) ; do \
-		case $$pkg in \
-			ffmpeg|*-dev) \
-				continue \
-				;; \
-			*avcodec*) \
-				soversion=$$(echo $$pkg | sed -nr 's/^[^0-9]*([0-9]+)$$/\1/p'); \
-				dh_makeshlibs -p $$pkg -V"libavcodec$$soversion (>= ${DEB_VERSION_EPOCH_UPSTREAM}) | libavcodec-extra$$soversion (>= ${DEB_VERSION_EPOCH_UPSTREAM})" \
-				;; \
-			*avfilter*) \
-				soversion=$$(echo $$pkg | sed -nr 's/^[^0-9]*([0-9]+)$$/\1/p'); \
-				dh_makeshlibs -p $$pkg -V"libavfilter$$soversion (>= ${DEB_VERSION_EPOCH_UPSTREAM}) | libavfilter-extra$$soversion (>= ${DEB_VERSION_EPOCH_UPSTREAM})" \
-				;; \
-			*) \
-				dh_makeshlibs -p $$pkg -V \
-				;; \
-		esac \
+override_dh_shlibdeps:
+	$(RM) debian/shlibs.local
+	set -e && for pkg in $(SHLIB_PKGS); do \
+		lib=`echo $$pkg | sed 's/\([a-z]*\)\([0-9]*\)/\1/'`; \
+		abi=`echo $$pkg | sed 's/\([a-z]*\)\([0-9]*\)/\2/'`; \
+		ver=${DEB_VERSION}; \
+		echo "$$lib $$abi $$pkg (= $$ver)" >> debian/shlibs.local; \
 	done
+	dh_shlibdeps
+
+override_dh_missing:
+	dh_missing --list-missing
 
 # Don't compress the example source code files.
 override_dh_compress:
